; contains routines for rendering text in a variable-width font to WRAM,
; and copying those tiles to VRAM

; 3800 to give layer 2 some extra space
TILE_DESTINATION_START = $3800

DEST_TILE_ID_START = $0
BYTES_PER_TILE = $10

; font types
FONT_TYPE_8X8 = 0
FONT_TYPE_8X16 = 1

vwf_set_font
.al
.xl
    sta vwf_font_base
    rts

vwf_set_palette
.al
.xl
    asl
    asl
    ; $21 = priority on, palette 0, tile ID high bits = 01 (256 + low byte)
    ora #$21
    xba
    sta vwf_tilemap_id_high_byte
    rts

; sets the font type for subsequent text rendering
; input: A - font type (FONT_TYPE_8X8 or FONT_TYPE_8X16)
vwf_set_font_type
.al
.xl
    sta vwf_font_type
    rts

vwf_frame_loop
.al
.xl
    lda text_box_enabled
    bne +
    rts

+   lda vwf_end_of_string
    bne _check_next_line

    ; keep going with current string
    lda #1
    sta vwf_count
    stz zp3
    jmp vwf_draw_string

_check_next_line
    lda text_index
    inc a
    cmp text_box_num_lines
    bne _init_next_line
    rts

_init_next_line
    sta text_index
    asl
    tay
    lda (text_box_lines), y
    pha

    lda text_index
    clc
    adc text_box_y
    tay
    iny

    ldx text_box_x
    inx

    pla
    jmp vwf_init_string

; call from vblank to transfer text tiles and do text box background HDMA
text_box_vblank
.as
.xl
    lda text_box_hide_requested
    beq +

    ; hide requested - disable everything and return
    rep #$20
    stz text_box_hide_requested
    stz text_box_enabled
    ; reset decision variables
    stz text_box_num_options
    stz text_box_active_option
    stz text_index
    sep #$20
    ; clear the text box window
    stz HDMAEN
    ; clear tiles and tilemap
    jsr vwf_reset_map
    ; get ready for the next text box
    jmp vwf_reset_tiles

    ; check if we should clear text but keep box visible
+   lda text_box_clear_requested
    beq +

    rep #$20
    stz text_box_clear_requested
    ; reset decision variables
    stz text_box_num_options
    stz text_box_active_option
    ; reset text state
    stz text_index
    sep #$20
    ; clear tiles and tilemap
    jsr vwf_reset_map
    ; get ready for the next text
    jsr vwf_reset_tiles

    bra _set_up_hdma

    ; no hide requested, no clear requested, is it even enabled
+   lda text_box_enabled
    bne +
    rts

    ; first send any new tiles generated by vwf_draw_string to VRAM.
    ; gotta do this before HDMA to avoid visual glitches
+   ldy vwf_dmalen
    beq _set_up_cursor
    jsr vwf_dma_tiles
    jsr vwf_transfer_map
    stz vwf_dmalen
_set_up_cursor
    jsr update_text_box_cursor

_set_up_hdma
    ; place text box at proper location, convert x tile to pixels
    ; this all only needs to be done once when the text box is shown
    ; todo: optimize
    lda text_box_x
    asl
    asl
    asl
    sta zp2
    sta WH0

    lda text_box_width
    asl
    asl
    asl
    clc
    adc zp2
    sta WH1

    ; convert y position to pixels
    lda text_box_y
    asl
    asl
    asl

    ; if < $80, subtract 2, and use in first hdma table entry
    ; (1 to account for necessary second entry, and 1 because hdma takes effect
    ; on the next line)
    ; second hdma entry should be 1

    cmp #$80
    bcs +
    dec a
    dec a
    sta text_box_hdma_table
    lda #$1
    sta text_box_hdma_table + 2
    bra _set_height

    ; otherwise first entry is 7f and second entry is y - $80
+   sec
    sbc #$80
    sta text_box_hdma_table + 2
    lda #$7f
    sta text_box_hdma_table

    ; set active region for color window in hdma table
    ; based on height of text box and font type
_set_height
    ldx text_box_num_lines
    lda vwf_font_type
    cmp #FONT_TYPE_8X16
    beq _use_8x16_heights
    
_use_8x8_heights
    lda TEXT_BOX_HEIGHTS, x
    bra _store_height
    
_use_8x16_heights
    lda TEXT_BOX_HEIGHTS_8X16, x
    
_store_height
    sta text_box_hdma_table + 4

    lda #$0
    sta DMAMODE
    lda #CGADSUB & $ff
    sta DMAPPUREG
    ldx #text_box_hdma_table
    stx DMAADDR
    stz DMAADDRBANK
    lda #$1
    sta HDMAEN

    rts

update_text_box_cursor
.as
.xl
    ; only update if we have options
    lda text_box_num_options
    bne +
    rts

    ; set VRAM increment to 1 word
+   lda #$80
    sta VMAIN
    rep #$20

    ldx text_box_num_options
    dex
-   txa
    asl
    tay
    cpx text_box_active_option
    bne _write_empty

_write_cursor
    lda text_box_option_positions, y
    sta VMADD
    lda #$21fb
    sta VMDATA
    bra _next

_write_empty
    lda text_box_option_positions, y
    sta VMADD
    lda #$0000
    sta VMDATA

_next
    dex
    bpl -
    sep #$20
    rts

; call this at the beginning of a text box
; - resets destination text tile pointer to beginning of WRAM output buffer
; - resets next tile pointer to the tile after that
; - resets VRAM pointer to the beginning of tile data for BG3 tileset
vwf_reset_tiles
    php
    rep #$20
.al
.xl
    lda #vwf_tiles
    sta vwf_dst

    ; set up pointers based on font type
    lda vwf_font_type
    cmp #FONT_TYPE_8X16
    beq _reset_8x16
    
_reset_8x8
    ; 8x8: vwf_next is just one tile ahead
    lda vwf_dst
    sta vwf_dst_bottom
    clc
    adc #BYTES_PER_TILE
    sta vwf_next
    sta vwf_next_bottom
    bra _dst_next_done
    
_reset_8x16
    ; 8x16: dst, dst_bottom, next, next_bottom
    lda vwf_dst
    clc
    adc #BYTES_PER_TILE
    sta vwf_dst_bottom
    adc #BYTES_PER_TILE  
    sta vwf_next
    adc #BYTES_PER_TILE
    sta vwf_next_bottom

_dst_next_done
    lda #TILE_DESTINATION_START
    sta vwf_dmadst

    ; incrementing tile counter
    lda #DEST_TILE_ID_START
    sta vwf_tilemap_id

    plp
    rts

; get ready to render the next string, call this at the beginning of each line
; input: A - address of string
;        X - x coordinate in tiles
;        Y - y coordinate in tiles
; assumes: AXY16
; uses vwf_font_type to determine 8x8 vs 8x16 rendering
vwf_init_string
.al
.xl
    sta vwf_src

    lda vwf_font_type
    bne _8x16

    lda vwf_dst
    clc
    adc #BYTES_PER_TILE
    sta vwf_dst
    adc #BYTES_PER_TILE
    sta vwf_next
    bra _continue

_8x16
    lda vwf_dst
    clc
    adc #BYTES_PER_TILE
    adc #BYTES_PER_TILE
    sta vwf_dst
    adc #BYTES_PER_TILE
    sta vwf_dst_bottom
    adc #BYTES_PER_TILE
    sta vwf_next
    adc #BYTES_PER_TILE
    sta vwf_next_bottom

_continue
    ; convert tile coordinates to layer 3 tilemap address
    ; $800 + (y << 5) + x
    tya
    asl
    asl
    asl
    asl
    asl
    sta vwf_tilemap_dst
    txa
    clc
    adc vwf_tilemap_dst
    adc #$800
    sta vwf_tilemap_dst

    stz vwf_offs
    stz vwf_end_of_string

    ; clear out first tile so nothing from the last string gets
    ; ORed into the one that it's about to draw
    lda #$0
    ldy #$e
 -  sta (vwf_dst), y
    sta (vwf_dst_bottom), y
    dey
    dey
    bpl -

    rts

; Renders text in variable-width font to tiles and returns the rendered text
; for copying to VRAM during the next blanking interval.
; vwf_src points to the currently processed char.
; vwf_dst points to the first byte of the current tile (in WRAM).
; input: vwf_src = address of string
;        vwf_count = count of characters to draw (-1 for everything)
;        zp3 = if 1, cross out text (for journal)
; returns: vwf_dmasrc = base address of rendered text to send to VRAM
;          vwf_dmadst = destination address for VRAM DMA
;          vwf_dmalen = number of tiles to send to VRAM
; assumes: AXY 16
vwf_draw_string
.al
.xl
    lda vwf_end_of_string
    beq +
    rts

    ; before doing anything set the return value
+   lda vwf_dst
    sta vwf_dmasrc
    stz vwf_dmasrcbank

; this is kind of crazy branching???
; surely i can optimize how this works
_check_count
    lda vwf_count
    ; if length parameter was negative, want whole string
    bmi _load_char
    dec vwf_count
    bmi _exit_length_parameter_reached

_load_char
    lda (vwf_src)
    and #$ff
    cmp #$ff
    sta vwf_ch
    bne _check_special_char

    ; end of string. next time called, return immediately
    inc vwf_end_of_string
    ; take into account any unfinished tiles this time
    lda vwf_next
    bra _set_dmalen_and_exit

_check_special_char
    ; check for $80 (option marker)
    cmp #$80
    bne _process_char

    ; save current tilemap position for this option
    lda text_box_num_options
    asl
    tax
    lda vwf_tilemap_dst
    sta text_box_option_positions, x

    inc text_box_num_options
    ; indent options a little bit for cursor
    inc vwf_tilemap_dst
    inc vwf_tilemap_dst

    ; move to next character
    inc vwf_src
    bra _check_count

_exit_length_parameter_reached
    ; calculate length used (in bytes)
    lda vwf_dst
_set_dmalen_and_exit
    sec
    sbc vwf_dmasrc
    sta vwf_dmalen

    rts

_process_char
    ; check font type to determine how to process character
    lda vwf_font_type
    cmp #FONT_TYPE_8X16
    beq _process_char_8x16

_process_char_8x8
    ; look up tile in font (go to last byte because it iterates backwards)
    ; vwf_font_ptr = GENEVA_CHARS + (16 * vwf_ch) + 15
    lda vwf_ch
    asl
    asl
    asl
    asl
    clc
    adc vwf_font_base
    adc #$f
    sta vwf_font_ptr

    ; for each byte in the current destination tile
    ldy #15
    jmp _each_byte_8x8

_process_char_8x16
    ; for 8x16 fonts with sequential top/bottom layout,
    ; we process each character as two separate 8x8 tiles
    ; first process top half, then bottom half
    
    ; calculate font pointer for top half: (vwf_ch * 32) + 15
    lda vwf_ch
    asl
    asl
    asl
    asl
    asl ; multiply by 32 for 8x16 chars
    clc
    adc vwf_font_base ; will need separate font data for 8x16
    adc #$f ; start from byte 15 for top half
    sta vwf_font_ptr

    ; process top half (first 16 bytes)
    lda #0  ; 0 = top half
    jsr _process_8x16_half_tile
    
    ; calculate font pointer for bottom half: same base + 31 (second 16 bytes)
    lda vwf_ch
    asl
    asl
    asl
    asl
    asl
    clc
    adc vwf_font_base
    adc #$1f ; start from byte 31 for bottom half
    sta vwf_font_ptr
    
    ; process bottom half (second 16 bytes)
    lda #1  ; 1 = bottom half
    jsr _process_8x16_half_tile
    jmp _char_processing_done

_each_byte_8x8
    sep #$20

    ; save existing tile byte
    lda (vwf_dst), y
    sta vwf_cur_tile_byte

    lda #0
    sta vwf_remainder

    ; loads equivalent byte from font for this char
    lda (vwf_font_ptr)

    ldx vwf_offs
-   beq _done_shifting_8x8
    ; remove the rightmost "vwf_offs" pixels
    lsr
    ; and store them in the remainder to be placed in the next tile
    ror vwf_remainder
    dex
    bra -

_done_shifting_8x8
    ; combine new partial character with existing tile
    ; 0 - transparent, 1 - black, 2 - black, 3 - white
    ora vwf_cur_tile_byte
    sta (vwf_dst), y

    ; leftover pixels need to go in the next tile
    lda vwf_remainder
    sta (vwf_next), y

    rep #$20

    dec vwf_font_ptr
    dey
    bpl _each_byte_8x8
    jmp _char_processing_done

; helper routine to process a single 8x8 tile in the 8x16 case
; input: A = 0 for top half, 1 for bottom half
_process_8x16_half_tile
    ; save which half we're processing
    sta zp2
    
    ldy #15
-   sep #$20

    lda zp2
    bne _save_bottom

    ; save existing tile byte from top tile
    lda (vwf_dst), y
    sta vwf_cur_tile_byte
    bra _process_font_data
    
_save_bottom
    ; save existing tile byte from bottom tile
    lda (vwf_dst_bottom), y
    sta vwf_cur_tile_byte

_process_font_data
    lda #0
    sta vwf_remainder

    ; loads equivalent byte from font for this char
    lda (vwf_font_ptr)

    ldx vwf_offs
    beq _done_shifting_tile
_shift_loop
    ; remove the rightmost "vwf_offs" pixels
    lsr
    ; and store them in the remainder to be placed in the next tile
    ror vwf_remainder
    dex
    bne _shift_loop

_done_shifting_tile
    ; combine new partial character with existing tile
    ora vwf_cur_tile_byte
    
    ; store back to appropriate tile and handle remainder
    ldx zp2
    bne _store_bottom_half

_store_top_half
    sta (vwf_dst), y
    ; remainder goes to next top tile
    lda vwf_remainder
    sta (vwf_next), y
    bra _continue_tile_loop
    
_store_bottom_half
    sta (vwf_dst_bottom), y
    ; remainder goes to next bottom tile
    lda vwf_remainder
    sta (vwf_next_bottom), y

_continue_tile_loop
    rep #$20

    dec vwf_font_ptr
    dey
    bpl -
    rts

_char_processing_done
    ; vwf_offs = (vwf_offs + CHAR_WIDTHS[vwf_ch]) % 8;
    ldx vwf_ch
    lda GENEVA_CHAR_WIDTHS, x
    and #$ff
    clc
    adc vwf_offs
    sta vwf_offs

    ; if vwf_offs < 8 move to next char
    cmp #8
    bmi _next_char
    ; was >= 8, so need to move to next dest tile
    and #7
    sta vwf_offs

    ; crossing out
    ; lda zp3
    ; beq +
    ; ldy #8
    ; lda #255
    ; sta (vwf_dst), y

    ldy vwf_font_type
    bne _advance_8x16

    ; 8x8
    lda vwf_next
    sta vwf_dst
    clc
    adc #BYTES_PER_TILE
    sta vwf_next
    bra _next_char

_advance_8x16
    lda vwf_next
    sta vwf_dst
    clc
    adc #BYTES_PER_TILE
    adc #BYTES_PER_TILE
    sta vwf_next

    lda vwf_next_bottom
    sta vwf_dst_bottom
    adc #BYTES_PER_TILE
    adc #BYTES_PER_TILE
    sta vwf_next_bottom

_next_char
    ; successfully completed this char without overflowing the tile
    ; onto the next char
    inc vwf_src

    ; all the crazy branching above is because there's no conditional relative long branch
    brl _check_count

; input: y = number of bytes to transfer
vwf_dma_tiles
.xl
    php
    sep #$20
    sty DMALEN
    ldx #DMAMODE_PPUDATA
    stx DMAMODE

    ldx vwf_dmasrc
    stx DMAADDR
    lda vwf_dmasrcbank
    sta DMAADDRBANK

    ldx vwf_dmadst
    stx VMADD
    lda #$80
    sta VMAIN

    lda #1
    sta MDMAEN

    ; advance vram pointer by however many words were written
    rep #$20
    lda vwf_dmalen
    lsr
    clc
    adc vwf_dmadst
    sta vwf_dmadst
    plp
    rts

; sets the tilemap (increasing tile id from 1) starting at the position
; vwf_tilemap_dst to tiles generated by vwf_draw_string and vwf_dma_tiles
; handles both 8x8 and 8x16 fonts
vwf_transfer_map
.xl
    php
    sep #$20
    lda #$80
    sta VMAIN
    rep #$20

    ldx vwf_tilemap_dst
    stx VMADD

    ; check font type to determine tilemap layout
    lda vwf_font_type
    cmp #FONT_TYPE_8X16
    beq _transfer_map_8x16

_transfer_map_8x8
    ; in BYTES, divide by 16 to get num tiles
    lda vwf_dmalen
    lsr
    lsr
    lsr
    lsr
    tax

    ; standard 8x8 font - one tile per character
-   lda vwf_tilemap_id
    ora vwf_tilemap_id_high_byte
    sta VMDATA
    inc vwf_tilemap_id
    inc vwf_tilemap_dst
    dex
    bne -
    bra _transfer_map_done

_transfer_map_8x16
    ; in BYTES, divide by 16 to get num tiles, then divide by 2 for character count
    lda vwf_dmalen
    lsr
    lsr
    lsr
    lsr
    lsr  ; divide by 2 since we process 2 tiles per character
    tax  ; save character count in X
-   ; write top tile
    lda vwf_tilemap_id
    ora vwf_tilemap_id_high_byte
    sta VMDATA
    inc vwf_tilemap_id
    
    ; save current position and move to next row for bottom tile
    lda vwf_tilemap_dst
    pha
    clc
    adc #32  ; next row in tilemap (32 tiles per row)
    sta VMADD
    
    ; write bottom tile
    lda vwf_tilemap_id
    ora vwf_tilemap_id_high_byte
    sta VMDATA
    inc vwf_tilemap_id
    
    ; restore position and move to next character column
    pla
    inc a
    sta vwf_tilemap_dst
    sta VMADD
    
    dex  ; decrement character counter
    bne -

_transfer_map_done
    plp
    rts

; clears the generated tiles in VRAM and the tilemap, call when a text box
; is supposed to disappear. only call from vblank
vwf_reset_map
.al
.xl
    php
    rep #$20

    lda vwf_tilemap_id
    sec
    sbc #DEST_TILE_ID_START
    bne +

    ; if equal nothing to do
    plp
    rts

    ; byte count to clear = 16 * num tiles used
+   asl
    asl
    asl
    asl
    sta DMALEN

    ldx #DMAMODE_PPUFILL
    stx DMAMODE

    sep #$20

    ldx #<>ZERO
    stx DMAADDR
    lda #`ZERO
    sta DMAADDRBANK

    ; clear tiles
    ldx #TILE_DESTINATION_START
    stx VMADD
    lda #$80
    sta VMAIN

    lda #1
    sta MDMAEN

    ; clear tilemap - actually only need to clear where the text box was
    ; future optimization
    ldx #$800 ; 400 words
    stx DMALEN
    ldx #$800
    stx VMADD
    lda #$1
    sta MDMAEN

    ldx #DEST_TILE_ID_START
    stx vwf_tilemap_id

    plp
    rts

static_char .macro
    lda #($21a0 + \1)
    sta VMDATA
.endmacro

; converts a nibble (0-15) to a hex character tile ID
; input: A = nibble value (0-15)
; output: A = tile ID for hex digit
; assumes: A16
nibble_to_hex_tile
.al
    and #$f
    cmp #$a
    bcs +
    adc #$10
    bra _done
+   clc
    adc #23 ; offset in font between beginning and 'A' excluding 0-9
_done
    adc #$21a0
    rts

; draws a bar graph representing a value in scanlines
; input: A = value (scanlines)
; assumes: A16, VMAIN/VMADD already set up, VMDATA ready for writes
draw_bar_graph
.al
    pha
    lsr
    lsr
    lsr  ; A = number of full 8-pixel bars
    beq _partial

    tax
-   pha
    lda #$2198  ; tile $2198 = full 8-pixel bar
    sta VMDATA
    pla
    dex
    bne -

_partial
    pla  ; restore original value
    and #7  ; get remainder (0-7)
    beq _blanks
    clc
    adc #$2190  ; tiles $2191-$2197 are 1-7 pixels (remainder + $2190)
    sta VMDATA

_blanks
    ; write some blank tiles to clear any leftover from previous frame
    lda #$2190
    sta VMDATA
    sta VMDATA
    sta VMDATA
    sta VMDATA
    sta VMDATA
    sta VMDATA
    sta VMDATA
    sta VMDATA
    sta VMDATA
    sta VMDATA
    rts

; is this even worth measuring because of how much time it adds
draw_cpu_usage
.xl
    php
    sep #$20
    lda #$80
    sta VMAIN
    rep #$20

    lda #$b42
    sta VMADD

    lda vertical_counter_this_frame
    jsr draw_bar_graph

    lda #$b62
    sta VMADD

    lda vertical_counter_vblank_this_frame
    jsr draw_bar_graph

    plp
    rts